<?php

/*
| User-provided visual references.
|
| These URLs inform future curation but are not imported into the visible feed.
| A profile only enters instagram_creators.php after its handle, identity,
| activity and recent formats pass the provider audit.
*/

return [
    [
        'handle' => 'alturasdesign.pt',
        'instagram_url' => 'https://www.instagram.com/alturasdesign.pt/',
        'vertical' => 'business',
        'market' => 'PT',
        'language' => 'pt',
        'topics' => ['brand design', 'agency', 'business branding'],
        'rationale' => 'Référence d’agence créative qui relie identité visuelle, stratégie de marque et développement commercial.',
        'source_urls' => [
            'https://www.instagram.com/alturasdesign.pt/',
            'https://www.alturascreativestudio.com/',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'softriver',
        'instagram_url' => 'https://www.instagram.com/softriver/',
        'vertical' => 'business',
        'market' => 'US',
        'language' => 'en',
        'topics' => ['brand design', 'logo design', 'agency business'],
        'rationale' => 'Référence d’agence orientée branding pour les startups et entreprises, avec une promesse commerciale très lisible.',
        'source_urls' => [
            'https://www.instagram.com/softriver/',
            'https://www.softriver.co/',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'zacharywinterton',
        'instagram_url' => 'https://www.instagram.com/zacharywinterton/',
        'vertical' => 'business',
        'market' => 'US',
        'language' => 'en',
        'topics' => ['graphic design', 'creative direction', 'agency business'],
        'rationale' => 'Référence de designer indépendant qui transforme une signature visuelle en offre créative destinée aux marques.',
        'source_urls' => [
            'https://www.instagram.com/zacharywinterton/',
            'https://infludata.com/de/rankings/top-20-influencer-united-states-of-america-portland-art-instagram',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'formd.designs',
        'instagram_url' => 'https://www.instagram.com/formd.designs/',
        'vertical' => 'business',
        'market' => 'IN',
        'language' => 'en',
        'topics' => ['brand identity', 'packaging', 'design process'],
        'rationale' => 'Référence de studio de brand identity et packaging, avec un contenu centré sur les projets et leur exécution.',
        'source_urls' => [
            'https://www.instagram.com/formd.designs/',
            'https://in.linkedin.com/in/shaurya-bharadwaj-806370317',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => '5feet.4',
        'instagram_url' => 'https://www.instagram.com/5feet.4/',
        'vertical' => 'business',
        'market' => null,
        'language' => null,
        'topics' => ['visual branding', 'creative direction', 'agency inspiration'],
        'rationale' => 'Référence visuelle fournie par l’utilisateur, identité et positionnement à vérifier avant toute classification plus précise.',
        'source_urls' => ['https://www.instagram.com/5feet.4/'],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'studio.no04',
        'instagram_url' => 'https://www.instagram.com/studio.no04/',
        'vertical' => 'business',
        'market' => null,
        'language' => 'en',
        'topics' => ['brand identity', 'packaging', 'art direction'],
        'rationale' => 'Studio de branding apprécié pour ses identités audacieuses, ses systèmes graphiques et ses cas clients.',
        'source_urls' => [
            'https://www.instagram.com/studio.no04/',
            'https://linktr.ee/studio.no04',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'hexonstudio',
        'instagram_url' => 'https://www.instagram.com/hexonstudio/',
        'vertical' => 'business',
        'market' => 'GB',
        'language' => 'en',
        'topics' => ['brand identity', 'visual systems', 'business design'],
        'rationale' => 'Studio de design orienté identité de marque, avec un angle très business et des applications digitales et physiques.',
        'source_urls' => [
            'https://www.instagram.com/hexonstudio/',
            'https://www.behance.net/hexonstudio',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'mixistudio',
        'instagram_url' => 'https://www.instagram.com/mixistudio/',
        'vertical' => 'business',
        'market' => null,
        'language' => 'en',
        'topics' => ['logo design', 'brand identity', 'premium branding'],
        'rationale' => 'Référence de studio proposant des identités premium et du contenu très démonstratif autour des logos et systèmes de marque.',
        'source_urls' => [
            'https://www.instagram.com/mixistudio/',
            'https://pictame.com/en/discover/hashtag/branding-studio',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'whysaksham',
        'instagram_url' => 'https://www.instagram.com/whysaksham/',
        'vertical' => 'personal-branding',
        'market' => 'IN',
        'language' => 'en',
        'topics' => ['personal branding', 'content strategy', 'business'],
        'rationale' => 'Créateur indien apprécié pour ses conseils directs sur la marque personnelle, le contenu et l’acquisition. À intégrer seulement si le marché IN est ouvert.',
        'source_urls' => [
            'https://www.instagram.com/whysaksham/',
            'https://linktr.ee/whysaksham',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => 'shauryadesigns',
        'instagram_url' => 'https://www.instagram.com/shauryadesigns/',
        'vertical' => 'personal-branding',
        'market' => 'US',
        'language' => 'en',
        'topics' => ['graphic design', 'brand identity', 'visual systems'],
        'rationale' => 'Référence visuelle à vérifier avant toute intégration comme créateur mesuré.',
        'source_urls' => [
            'https://www.instagram.com/shauryadesigns/',
            'https://www.freelancer.ca/u/shauryadesigns',
        ],
        'status' => 'reference_only',
    ],
    [
        'handle' => null,
        'instagram_url' => 'https://www.instagram.com/p/DbTV_ILkQW1/?img_index=1',
        'vertical' => 'personal-branding',
        'market' => null,
        'language' => null,
        'topics' => ['visual reference', 'carousel'],
        'rationale' => 'Post fourni comme référence de direction artistique et de format carousel.',
        'source_urls' => ['https://www.instagram.com/p/DbTV_ILkQW1/?img_index=1'],
        'status' => 'reference_only',
    ],
    [
        'handle' => null,
        'instagram_url' => 'https://www.instagram.com/p/DbVP68dgw0d/',
        'vertical' => 'personal-branding',
        'market' => null,
        'language' => null,
        'topics' => ['visual reference'],
        'rationale' => 'Post fourni comme référence de composition et de traitement éditorial.',
        'source_urls' => ['https://www.instagram.com/p/DbVP68dgw0d/'],
        'status' => 'reference_only',
    ],
    [
        'handle' => null,
        'instagram_url' => 'https://www.instagram.com/reel/DSnemIwkfxL/',
        'vertical' => 'personal-branding',
        'market' => null,
        'language' => null,
        'topics' => ['visual reference', 'reel'],
        'rationale' => 'Reel fourni comme référence de rythme, de montage et de format vidéo.',
        'source_urls' => ['https://www.instagram.com/reel/DSnemIwkfxL/'],
        'status' => 'reference_only',
    ],
    [
        'handle' => null,
        'instagram_url' => 'https://www.instagram.com/p/DbEruPKxMYy/',
        'vertical' => 'personal-branding',
        'market' => null,
        'language' => null,
        'topics' => ['visual reference', 'carousel'],
        'rationale' => 'Post fourni comme référence de contenu à étudier avant reproduction éditoriale.',
        'source_urls' => ['https://www.instagram.com/p/DbEruPKxMYy/'],
        'status' => 'reference_only',
    ],
    [
        'handle' => null,
        'instagram_url' => 'https://www.instagram.com/p/CPxuaAGBO9q/',
        'vertical' => 'personal-branding',
        'market' => null,
        'language' => null,
        'topics' => ['visual reference'],
        'rationale' => 'Ancienne référence fournie pour conserver les codes visuels appréciés.',
        'source_urls' => ['https://www.instagram.com/p/CPxuaAGBO9q/'],
        'status' => 'reference_only',
    ],
];
